dist: trusty
group: stable
os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  # * trusty does not have ffmpeg in the software repository, and must be added
  #   manually
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update -qq
  # * CMAKE can be manually installed through boutPPInstall.sh
  # * gfortran is usually installed on the clusters, if not it can be
  #   installed through gccLocalInstall.sh
  # * ffmpeg is installed through sudo as the build takes time, can also be
  #   installed through gccLocalInstall.sh
  - sudo apt-get install -qq cmake gfortran ffmpeg

install:
  - . ./install/boutPPInstall.sh

before_script:
  # Redirect stdout and stderr back to 1 and 2
  - exec 1> /dev/tty
  - exec 2> /dev/tty
  # TRAVIS_BUILD_DIR is the directory of the build
  - cd $TRAVIS_BUILD_DIR

script:
  # Check that celma is working
  - cd celma
  - python testScan.py
  - python testPostProcessing.py
  # Check that celma with the Boussinesq approximation is working
  - cd ../celmaWithBoussinesqApprox
  - python testScan.py
  - python testPostProcessing.py
  # Check that the MES is working
  - cd $TRAVIS_BUILD_DIR/MES/singleOperators/1-DDXCylinder
  - python driverGaussianWSinAndParabola.py
