dist: xenial
group: stable
os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get install -qq cmake gfortran
  - sudo apt-get install -qq mpich libmpich-dev
  - sudo apt-get install -qq libfftw3-dev
  - sudo apt-get install -qq libnetcdf-dev libnetcdf-cxx-legacy-dev libhdf5-serial-dev libhdf4g-dev
  - sudo apt-get install -qq ffmpeg
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.10.1.0 /usr/lib/x86_64-linux-gnu/libhdf5.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.10.0.2 /usr/lib/x86_64-linux-gnu/libhdf5_hl.so

install:
  - . ./install/install_conda.sh
  - pip install bout_install
  - bout_install -c $TRAVIS_BUILD_DIR/install/travis_install.ini

# TODO: Make new tests
#script:
#  # Check that celma is working
#  - cd celma
#  - python testScan.py
#  - python testPostProcessing.py
#  # Check that celma with the Boussinesq approximation is working
#  - cd ../celmaWithBoussinesqApprox
#  - python testScan.py
#  - python testPostProcessing.py
#  # Check that the MES is working
#  - cd $TRAVIS_BUILD_DIR/MES/singleOperators/1-DDXCylinder
#  - python driverGaussianWSinAndParabola.py
