dist: trusty
group: stable
os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake gfortran

script:
  # Install BOUT++ (could not redirect output under "install:")
  - ./install/boutPPInstall.sh
  # Test the build
  - ./celma/testScan.py
  - ./celma/testPostProcessing.py
  - ./celmaWithBoussinesqApprox/testScan.py
  - ./celmaWithBoussinesqApprox/testPostProcessing.py
