dist: xenial
group: stable
os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get install -qq mpich libmpich-dev
  - sudo apt-get install -qq libfftw3-dev libnetcdf-dev libnetcdf-cxx-legacy-dev
  - sudo apt-get install -qq python3 python3-pip python3-numpy python3-netcdf4 python3-scipy
  - sudo apt-get install -qq cmake gfortran ffmpeg

install:
  - pip3 install bout_install
  - bout_install -c .travis_install.ini


# TODO: Make new tests
#script:
#  # Check that celma is working
#  - cd celma
#  - python testScan.py
#  - python testPostProcessing.py
#  # Check that celma with the Boussinesq approximation is working
#  - cd ../celmaWithBoussinesqApprox
#  - python testScan.py
#  - python testPostProcessing.py
#  # Check that the MES is working
#  - cd $TRAVIS_BUILD_DIR/MES/singleOperators/1-DDXCylinder
#  - python driverGaussianWSinAndParabola.py
