dist: trusty
group: stable
os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake gfortran

install:
  - . ./install/boutPPInstall.sh

script:
  # Test the build
  - . ./celma/testScan.py
  - . ./celma/testPostProcessing.py
  - . ./celmaWithBoussinesqApprox/testScan.py
  - . ./celmaWithBoussinesqApprox/testPostProcessing.py
