# Find the home, since ~ does not work in general
# shell runs a shell command
HOME	= $(shell echo ~)
BOUT_TOP	= $(HOME)/BOUT-dev

SOURCEC		= DDXCylinderWithJacobianOverJacobian.cxx

include $(BOUT_TOP)/make.config
